name: ci

on:
  - push

jobs:
  docker:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            PASSWORD_HASH=${{ secrets.PASSWORD_HASH }}
            CAPTCHA_KEY=${{ secrets.CAPTCHA_KEY }}
            CAPTCHA_SECRET=${{ secrets.CAPTCHA_SECRET }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}